### ISSUE TITLE
Project plan

### ISSUE THREAD

**Issue by eyzhang24** [stat231-f21/blog_five-chives#1]
**Do you plan on your final project being an extension of your mid-semester project? Describe what you want to deliver as your final product.**

Yes, we plan on building off of our Shiny app mid-semester project. We plan to build off of our map visualization. We want to make this map interactive using the `leaflet` package.

The first map will integrate data from the CDC and add layers where we can visualize the locations of superfund sites. That same map will also track data over time (perhaps including an option to visualize changes over the years). We will use the `leaflet` package to allow users to zoom in on certain regions.

The second map will have interactivity linked to additional informative plots about specific variables in the data set. It will integrate both the EPA and CDC data sets to allow users to view relationships with a specific variable at that state over time. It will also include descriptive statistics for specific states and users will be able to zoom in and out. 

Finally, our third visualization will build a network that shows correlations between references to health key words and toxicity key words in US Congress legislation, which would require us to add additional data. This would also involve web scraping and text analysis. We are interested in assessing how much attention is paid in legislation to the correlation between these two variables. Assessing this relationship over time would see whether these actions are changing. We may also create a wordcloud to see the most commonly used words in US legislation regarding this topic. 

We are also interested in potentially building predictive models using a correlation analysis between sociodemographic, environmental, and mortality variables. We will look into models that we might be able to use to determine whether this will be feasible. We expect that the correlations between these variables have been increasing due to rising inequality and toxicity release over time; our model would forecast this correlation. This would include correlation plots for the years that have already passed, and correlation plots for the coming years. 

**Schedule:**
_11/02: Project Plan Due
11/05:_ 

- Complete any additional wrangling, finalize ideas, and determine what is feasible

_11/09: Status Update 1_

- Have rough template of visualizations

_11/16: Status Update 2_

- Have rough template of how we want our page to be organized
- Finalize visualizations

_11/19:_

- Have template of how we want our page to be organized
- Have working drafts of our written pieces

_11/30: Presentation_

- Working blog post

_12/07:_ 

- Edit everything and have it completely ready to submit!

_12/09: Blog Post Due_

**Comment by bebailey** [comment]
For your third visualization, have you checked the feasibility of scraping the legislative text? 

For the predictive models, I am not sure if I am fully understanding the intention of predicting correlations. With predictive modeling, we leverage the association between variables to try to predict something of interest (e.g., using sociodemographic and/or environmental characteristics to predict mortality rates). It sounds like you are thinking of modeling some set of correlations themselves as outcomes, looking at how the specific correlations change over time, and trying to then predict the same set of correlations in future years? This sounds possible, but you'll also want to make sure correlation is an appropriate measure of the association between any pair of variables of interest. 

This was not part of the requirement, but please make sure you discuss amongst yourselves exactly how you plan to divide up the work. Perhaps it would be useful to write it down as a sort of group contract, even. To the degree possible, we want equitable contributions to the core components of the blog, with flexibility for any individual to go "above and beyond" on any particular aspect of interest to them. 

---

To embed a shiny app, you can use a code chunk (see [this link](https://bookdown.org/yihui/bookdown/web-pages-and-shiny-apps.html) for details):

```
knitr::include_app("https://your-account.shinyapps.io/your-app/", height = "600px")
```

**Comment by caitlinlambert** [comment]
### Status Update 1

Our goal for up to this point was to create rough templates of our visualizations. 

Caitlin: For the first map, with a choropleth and marker layer with `leaflet` functionality, I was able to create a mock-up of such a map but without the functionality to choose the variable shown on the choropleth map and if the markers for the superfund sites are present. I had to spend some extra time to wrangle the necessary data for creating choropleth maps in `leaflet` and join it with our data from the CDC. Creating this in Shiny App has proven to be a bit tricky in order to work out the necessary reactive and observer objects, so it’s not fully functional yet, but I hope to polish it up by the end of the week. 

Elizabeth: For the text analysis, I ended up deciding to scrape scientific research abstracts, rather than legislation. I scraped all abstracts from Pubmed from a search with the following keywords: “mortality” and “cause” or “determinant”. I did a text analysis on these abstracts. I created a list of words of interest that I wanted to assess (for example, words like “results” or “mortality” wouldn’t reveal any interesting information, so I chose to exclude them). I created an interactive visualization on Shiny that allows the user to choose a year and see the top 10 words of interest that appeared in abstracts that year, along with a network of the top 10 words. I would like to add in an animation feature on the year selection. I also want to collect a static list of words of interest to keep in the network, rather than top 10 per year, and see if I can keep their locations constant despite year selection. 

Dasha: For the second map, I was able to load a map of the United States that is outlined by county and state. The county map data allowed me to join it with our current data in order to have that functional data set. The aim for this map is to allow users to zoom into specific states of interest and view the relationship between variables of interest and median income level for the specific state. They should also be able to view quick summary statistics. I’ve been able to create interactivity to choose variables of interest and a static map.  I’ve worked with the `leaflet` package and began setting up the foundations of my Shiny App. However, I still need to work on allowing users to view the relationships between the variables upon zooming into a specific state. I had a really busy past 2 weeks of exams, but since that period is coming to an end for me, I intend to dedicate substantially more time to the project later this week and during the entirety of next week. I expect to have a working app before Thanksgiving break.

**Comment by dashaasienga** [comment]
### Status Update 2

Caitlin: I have finalized a working version of my visualization that allows the user to interact with a leaflet by presenting several environmental and health factors to choose to display on the choropleth map. In addition, the user can choose whether or not to display Superfund sites. Working out how to color the maps within Shiny was particularly difficult and took me a while. I would like to add more details on the visualization of the data through subtitles if possible. I also still need to add this visualization to our final index.rmd and create a write-up about my visualization for our blog post.

Elizabeth: I have fine-tuned my visualizations. I have an animated gif of a bar chart of top ten words used in research abstract over time, and I also have an interactive Shiny visualization where users can choose a year and words of interest to view in a network. The network connects words used in the same abstract. I have drafts of an introduction, data collection methods, descriptions of visualizations, and limitations and future directions. I want to include literature references in the introduction, identify specific questions of interest, include extra information in the data collection process, include example code in the html output, and draft some overarching conclusions. 

Dasha: I have a working version of my visualization. Users are able to interact with a map of the United States by viewing a choropleth map. They are able to view the map of the US as a whole, or zoom into the specific states. They can also select which variables are of interest. Upon selecting a state of interest and a variable of interest, users are able to view an accompanying scatterplot of median income level plotted against the variable of interest. Points are colored by whether the county is a national priority site or not. If interested, users can view whether their counties are superfund sites as well as where their county of interest lies in relation to the other counties in the state of interest. I’m feeling good about where I am, given that I plan on allocating a lot more time to the project this week. By the end of Thursday, I plan on increasing the interactivity of my map such as a hover feature with summary statistics as well as ability to zoom in and out. I also want to add an additional informative plot for each state to accompany the scatterplot, but that should be pretty quick. By the end of the week (Friday), I plan to have working drafts of the write-ups about my visualization. I’ll spend part of Thanksgiving break then doing the final fine-tuning.
